[project]
name = "flickr2blog"
version = "0.1.2"
description = "Replace flickr images in wordpress blog"
readme = "README.md"

requires-python = ">=3.9, <3.11"
dependencies = [
    "dynaconf",
    "flickrapi", 
    "requests",
    "setuptools"
]

[project.scripts]
flickr2blog = "flickr2blog:main"

